### PR TITLE
Some fixes and changes

### PR DESCRIPTION
**Pull request by Real-Gecko**
- Fix error: RelatedObjectDoesNotExist: User has no userattributes.
  "instances/views.py", line 162, in check_user_quota

### CODE REVIEW

**Comment by retspen** [comment]
Good job. Thank you!

**Comment by Real-Gecko** [comment]
Some more changes are on the way, beware :D

**Comment by Real-Gecko** [comment]
> why did we remove show logs? there are two logs: 1. instance specifi logs, 2. general logs

Logs are moved to admin app, however I don't remember any general logs. Can you point me to changes where I removed them, maybe I missed 'em somehow, and if so I'll fix it.

**Comment by catborise** [comment]
@Real-Gecko after moving settings.py default settings to "appsettings( on my bootstrap45 branch)" require the logs for changes. that but it does not matter we will figure it out somehow.

**Pull request merged**
