### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by savichev**
Warning! this string installing libxml2-python version 2.9.2

### CODE REVIEW

**Comment by retspen** [comment]
I think that it would be better:
```
https://github.com/GNOME/libxml2/archive/v2.9.2.tar.gz#egg=subdir&subdirectory=python
```

**Comment by savichev** [comment]
No! :-)
I think that it would be better:
```
git+https://git.gnome.org/browse/libxml2.git@v2.9.1#egg=subdir&subdirectory=python
```
:100:

**Comment by retspen** [comment]
No problem I can added https://github.com/GNOME/libxml2/archive/v2.9.2.tar.gz#egg=libxml2-python&subdirectory=python

**Comment by retspen** [comment]
I don't like scheme like git+https

**Comment by savichev** [comment]
git scheme download from the official repository and use tag
https://git.gnome.org/browse/libxml2/tree/?h=v2.9.1

**Comment by retspen** [comment]
I just have tested it on pip 7.0.x and less and pip can't find setup.py but with https - works fine.

**Comment by retspen** [comment]
Maybe try that URL:
```
http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz#egg=libxml2-python&subdirectory=python
```

**Comment by savichev** [comment]
```
IOError: [Errno 2] No such file or directory: '/tmp/pip-build-zUi_C7/libxml2-python/setup.py'
```

**Comment by retspen** [comment]
I have the same but for git+http. What version pip do you use?

**Comment by savichev** [comment]
```
pip 8.1.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```
need
```
sudo pip install --upgrade pip
```

**Comment by retspen** [comment]
```bash
$ pip install "http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz#egg=libxml2-python&subdirectory=python"
Collecting libxml2-python from http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz#egg=libxml2-python&subdirectory=python
  Downloading http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz
     - 4.9MB 499kB/s
Building wheels for collected packages: libxml2-python
  Running setup.py bdist_wheel for libxml2-python ... done
  Stored in directory: /Users/retspen/Library/Caches/pip/wheels/9d/6a/30/8e4846450ad1b2e68cb3b9ebdee65c21d220d18a4ce2806c48
Successfully built libxml2-python
Installing collected packages: libxml2-python
Successfully installed libxml2-python-2.9.1
```

**Comment by savichev** [comment]
Yes! Worked! =)

**Comment by savichev** [comment]
I did
```
sudo pip install --upgrade http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz#egg=libxml2-python&subdirectory=python
[1] 5626
savicheva@N3010:~ > The directory '/home/CHGRP_RU/savicheva/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/CHGRP_RU/savicheva/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting libxml2-python from http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz#egg=libxml2-python
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz
     - 5.6MB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-iU_4xC/libxml2-python/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iU_4xC/libxml2-python/

[1]+  Выход из 1       sudo pip install --upgrade http://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.1.tar.gz#egg=libxml2-python
```

**Comment by retspen** [comment]
You forgot about symbol <code>&</code> use <code>"</code>

**Comment by retspen** [comment]
Fix the URL in requirements.txt than I will approve the pull request.

**Pull request merged**
