### PR TITLE
Django version requirement, Libxml2->lxml change, account detail validation add, some bugs

### PR DESCRIPTION
**Pull request by catborise**
Hi retspen,
Thanks for all your efforts. I know you are very busy. I want to help some development for this project.
I am using webvirtmgr for a long time, i appreciate...
I try to use webvirtcloud and it is a great work. But i get some hiccups while installing and using.

1. libxml2 package cannot find easily anymore. Libxml2 developer create another project which is lxml. (https://lxml.de/3.6/FAQ.html) there are many more change and development about memory management, etc. I convert libxml2 to lxml. It requires some code changes on utils.py and hostdetails.py

2. Django version. When i try to use django 1.11 there are some changes need to be done with urls especially auth urls. I made them.

3. There were some problems with admin user and user attributes and its forms. I modify them to make form more strict with validators.(without validation characters make it crash)

### CODE REVIEW

**Comment by Bandic007** [comment]
@catborise @retspen - I've also made some changes and I will explain what.
@catborise  - I've pulled the project from your repo and installed it but immediately I've got some problem - the login page was not working. The problem was somewhere in the new way that you defined some variables in the /accounts/urls.py - I've used the original file from retspen repo and it worked. You can take a look there to see why it was not working as I have just little understanding of python and was not able to catch the issue. However - I was able to login. Then I had a second issue - Whet I tried to open the Instances page - it was not loading too -  The problem was that you've forgot to change one line where you are calling for a variable that you defined earlier in the code. It is on line 88 of instances/views.py file.
The line:
check_uuid = Instance(compute_id=comp.id, name=vm, uuid=info['uuid'])
should be:
check_uuid = Instance(compute_id=comp["id"], name=vm, uuid=info['uuid'])

I've uloaded the fixed version in my repo for WebVirtCloud, but you can fix those before merging your code with @retspen repo! Take a look on those!
Also I will be thankfull if you take a look at the accounts/urls.py file and tell me if it is ok to be change with @retspen original file in your update build @catborise

**Comment by retspen** [comment]
Thank you!

**Comment by Bandic007** [comment]
@retspen - In you merger I can see that you haven't modified the 2 problematic files. Whoever clone the repo will have the same issues as I did.
Do you want me to create a pull request and you just to merge the fixed files or you will fix them by yourself?

**Comment by catborise** [comment]
@Bandic007 sorry bandic, because of holiday i havent see your comment. I think it is now resolved. Thank you. 
I made some changes after your corrections. If restspen accept i will send..

**Pull request merged**
