### PR TITLE
Fix Port configuration for novncd

### PR DESCRIPTION
**Pull request by shokinn**
Revert accidentally change variable for novncd port configuration.

Change variable `WS_PUBLIC_PORT` back to `WS_PORT`

### CODE REVIEW

**Comment by retspen** [comment]
Hello,

I'm not sure about that changes.  WS_PUBLIC_PORT variable need for fronted side and use for redirect or URL open.

**Comment by lord-kyron** [comment]
@retspen - this is not a change but a fix as in the last commit @catborise changed this in the wrong place and VNC stopped working for us. That is why @shokinn is reverting this back as we tested it and that was the problem.

**Comment by shokinn** [comment]
Yupp.
Thanks @lord-kyron for clarifying!

@retspen See discussion here: https://github.com/retspen/webvirtcloud/pull/343#discussion_r469450856

**Comment by retspen** [comment]
I understood. Thanks for help!

**Comment by lord-kyron** [comment]
@shokinn  - you can join the official Webvirtcloud Discord channel here:
https://discord.gg/WVbkSW
There we can discuss and fix issues faster and easier on chat :)

**Pull request merged**
