### PR TITLE
Max length increased and public port

### PR DESCRIPTION
**Pull request by t-tran**
* Updat max length in a bunch of places to 64 chars
* Add setting `WS_PUBLIC_PORT` to support this running behind a reverse proxy such as nginx+ssl

### CODE REVIEW

**Comment by lord-kyron** [comment]
@t-tran - what config should I use on the nginx when reverse-proxying to webvirtcloud with enabled websocket public port? At the moment I am doing this almost the same way, but I also have ws_public_path which is '/novncd/' and in nginx I am proxying this specific location to localhost:6080 in order to work. Can you give and example config or explain how is it supposed to work your way?

**Comment by t-tran** [comment]
Hi @lord-kyron, I'm running reverse-proxy + SSL on standard https port 443 which has nginx config looks like this:
```
upstream novnc_server {
    server back.end.server.ip:6080;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    location /websockify {
        proxy_http_version 1.1;
        proxy_pass http://novnc_server/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 61s;
        proxy_buffering off;
    }
```

Since the frontend port (443) is different from backend port (6080). I need this setting so it routes correctly.

**Comment by lord-kyron** [comment]
Thank you! Working like a charm now!

**Comment by retspen** [comment]
Thank you!

**Comment by lord-kyron** [comment]
@t-tran do you have exprience with several compute nodes? For example will vnc work if I try to open the console on a VM which is on another compute node, different from the one that webvirtcloud is installed, but added as compute in the web interface?

**Comment by catborise** [comment]
> Hi @lord-kyron, I'm running reverse-proxy + SSL on standard https port 443 which has nginx config looks like this:
> 
> ```
> upstream novnc_server {
>     server back.end.server.ip:6080;
> }
> 
> server {
>     listen 443 ssl;
>     listen [::]:443 ssl;
>     location /websockify {
>         proxy_http_version 1.1;
>         proxy_pass http://novnc_server/;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_read_timeout 61s;
>         proxy_buffering off;
>     }
> ```
> 
> Since the frontend port (443) is different from backend port (6080). I need this setting so it routes correctly.
@t-tran 
could you please prepare a wiki page for reverse-proxy. it could be useful for ones who have to use that. 
thanks

**Pull request merged**
