### PR TITLE
Bigupdates

### PR DESCRIPTION
**Pull request by catborise**
Hi retspen it is a big update:

* Add localization choose options / add locale files
* Bootstrap 4.5 migration
* Bootswatch Themes addition & Theme selection
* Theme change settings With sass.
* Python 3 style updates
* Many fixes
* Move settings to appsettings for online changing.
* Fix typos
and fix some problems...

### CODE REVIEW

**Comment by retspen** [comment]
God job. Big thanks!

**Comment by Real-Gecko** [comment]
Hey, guys! I’m currently on vacation, will be back in a few days and will contribute more to the project, see ya.

**Comment by catborise** [comment]
@Real-Gecko we are looking forward your contributions. they are really precious... see you :)

**Comment by retspen** [comment]
Thank you guys!

**Pull request merged**
