### PR TITLE
NWFilters Addition & Instances Tab & Other Fixes

### PR DESCRIPTION
**Pull request by catborise**
Hi retspen,

1. NWFilters on libvirt added to domains and computes.
2. Adding/deleting/updating nwfilter rules/references.
3. Instance Network tab customized and fixed change operation. 
   - Add network delete option.
   - some bugs resolved with network change/add
4. Making owner(uid,gid) of vm image choosable using settings.py
5. Add instances tab to computes.(minimal changing, trying to keep structure as design)
6. Error Fixes
7. Favicon url fix
8. Fontawesome update
9. Hypervisor info revisited
10. Cache for disk option linked to settings.py
11. Add volume operations(attach new/existing, detach, delete)
12. honza801 fixes on master 
13. VM create menu change (collapse -> tab)

Ps. to make it work update settings.py and add nwfilters to apps
please accept it.
Thanks.

### CODE REVIEW

**Comment by catborise** [comment]
@Bandic007 hi bandic,
it is long running but i will merge all @honza801 commits and add, detach volumes, add new volume, add existing volume, delete volume functions.

i can make them really disable. but default behaviour is as implemented.
may be, anyone want to detach a disk for now to apply after shutdown.  because of that i will change alert to specify that situation (not disable really).

**Comment by catborise** [comment]
@Bandic007 as i said it is a default behaviour for virt-manager/libvirt. So it is a feature not a bug.
 You can detach a disk, although instance is running.

I modify dropdown menu to show selected pool.

Also, i want to add that dropdown. it seems usable.
https://github.com/snapappointments/bootstrap-select ( intuitive multiselection, searching, and much more)

**Comment by Bandic007** [comment]
@catborise - ok, sounds great!
The new changes are working fine and as I expected. Also the dropdown menu style that you proposed is really cool! I would like to see it implemented!

**Comment by catborise** [comment]
i think changes does not seen apropriate by retspen....

thanks, i am pulling back.

**Comment by retspen** [comment]
Sorry guys I don't have free time. Big thanks!

**Pull request merged**
