### PR TITLE
Fixed migrations for new deployments, added unit tests

### PR DESCRIPTION
**Pull request by Real-Gecko**
So, putting all those RunPython inside migrations was a bad idea, breaking migrations for new installs and unit tests. Here are some fixes. Moved admin creation and migration of `can clone` to post_migrate signals, which is not that exciting, but better than fixtures or some other workarounds.
`can_clone_instances` user attribute is in the model again, but is hidden from forms. If you're planning new release I think it's better to remove it at all and recreate all migrations from scratch.

### CODE REVIEW

**Comment by Real-Gecko** [comment]
Test are rather primitive, just checking that views return status code 200, but at least we know that nothing is broken during dev process.

**Comment by catborise** [comment]
@Real-Gecko nice touches thanks. 
i am working on bootstrap 4.5 migration, theme support, localization and move settings to html page.
merging can be very painful :)

**Comment by Real-Gecko** [comment]
You can try and cherry pick commits that do not interfere with you work, those that add unit tests and fix migrations won't affect your work I think. However 5ab22ba9475d843d513e6ad915a1902a594e4845 might be troublesome.
I want to reach high test coverage for project, it will help in further development. Current is 32%.
image

**Comment by catborise** [comment]
@Real-Gecko yea i start to merge...
test units will be very helpful. i really needs that. But i havent write any test. so, thanks for that. these additions will be life saver.

may be we should not use django-bootstrap3 package .
i want to use scss files with bootstrap 4.5

**Comment by Real-Gecko** [comment]
Here is one more, it adds coverage.py support. I use following two VSCode tasks to generate and view coverage report:
```json
{
    "label": "Run Tests with Coverage",
    "type": "shell",
    "command": "venv/bin/coverage run --source '.' --omit 'venv/*' manage.py test",
},
{
    "label": "Coverage Report",
    "type": "shell",
    "command": "venv/bin/coverage html && firefox ${workspaceFolder}/htmlcov/index.html",
}
```

**Comment by Real-Gecko** [comment]
> @Real-Gecko yea i start to merge...
> test units will be very helpful. i really needs that. But i havent write any test. so, thanks for that. these additions will be life saver.
> 
> may be we should not use django-bootstrap3 package .
> i want to use scss files with bootstrap 4.5

There's [django-bootstrap4 package](https://django-bootstrap4.readthedocs.io/en/latest/) that's the same in terms of tags to bootstrap3, migration won't be hard, I think it's even possible to coinstall them side by side and migrate to BS4 gradually. There's also [django-icons](https://django-icons.readthedocs.io/en/latest/) package which is continuation of django-fontawesome.

**Comment by Real-Gecko** [comment]
Using template helpers is of course debatable, but they help to speed up development dramatically.

**Comment by Real-Gecko** [comment]
> @Real-Gecko yea i start to merge...
> test units will be very helpful. i really needs that. But i havent write any test. so, thanks for that. these additions will be life saver.
> 
> may be we should not use django-bootstrap3 package .
> i want to use scss files with bootstrap 4.5

Can you share your work with PRs? Maybe we can split up the load on several devs.

**Comment by retspen** [comment]
Thank you!

**Pull request merged**
