### PR TITLE
New additions, changes

### PR DESCRIPTION
**Pull request by catborise**
Hi retspen,

There are a lot changes:
1. Edit instance disk capability is added.
2. Add new disk options for instance disk.
3. Instance network tab rearranged to show ipv6 and ipv4 addresses.
4. Show instance network driver model/change capability
5. Some bugs, typo and minor improvements like notification.

thanks

### CODE REVIEW

**Comment by retspen** [comment]
Thank you!

**Comment by FrancescoFdd5** [comment]
I tried to update and when I give the command:
`python manage.py migrate`
I get this error:
`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks    new_errors = check(app_configs=app_configs)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver    return check_method()
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/webvirtcloud/webvirtcloud/urls.py", line 12, in <module>
    url(r'^computes/', include('computes.urls')),
  File "/srv/webvirtcloud/venv/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/webvirtcloud/computes/urls.py", line 5, in <module>
    from create.views import create_instance, create_instance_select_type
  File "/srv/webvirtcloud/create/views.py", line 19, in <module>
    from webvirtcloud.settings import INSTANCE_VOLUME_DEFAULT_IO
ImportError: cannot import name INSTANCE_VOLUME_DEFAULT_IO`

**Comment by catborise** [comment]
@FrancescoFdd5 after the upgrade you should always check settings.py.template file to see there are some new default variables. If it is, then copy it to settings.py file

The error indicates that:
"<module> from **webvirtcloud.settings** import INSTANCE_VOLUME_DEFAULT_IO ImportError: cannot import name INSTANCE_VOLUME_DEFAULT_IO"

**Comment by FrancescoFdd5** [comment]
Resolved thanks

**Pull request merged**
