### PR TITLE
create instance from template enhanced and others

### PR DESCRIPTION
**Pull request by catborise**
Hi,
Create instance from template was does not work as expected.
1. Domain Capabilities info added
2. Get list of video graphics from domain capabilities
3. Get list of bus choices from domain capabilities(before that it was static info)
4. While creating instance with template choice, vm was creating with console password and local listener and network-filter. These are converted to selectable.
5. Add progress bar to creation of vm.
6. Check  destination image before cloning template, if it is exist or not.
7. Update bootstrap-table-min to 0.8
9. Make grouped instance view foldable(by @honza801 )
10. show vdi url on access tab.

if you merge it. i will appreciate.
thanks.

### CODE REVIEW

**Comment by catborise** [comment]
@Bandic007 okey. i did that changes from only create from template. but now it work for create from flavour and custom. showPleaseWaitDialog() is in webvirtcloud/pleasewaiddialog.html

emulator value is interesting. the value gets from capabilities xml("/capabilities/guest/arch/emulator").
can you send me "virsh capabilities" output.

**Comment by Bandic007** [comment]
I will send you yes but I've just cloned your repo and tried it. I can see the waining page but the VM is not being created. I am waiting just for a second and them no vm is created. This is when trying from flavor. I will now try from template.

**Comment by catborise** [comment]
with latest commit create from template/custom/flavour looks like below
image

image

image

**Comment by Bandic007** [comment]
Yes, I've just implemented it and the creation prompt looks like this. The problem is when I fill everything and click create I can see the please wait page for just 1 second and it dissapers and no VM is created at all.

**Comment by Bandic007** [comment]
about the other problem with the emulator in the compute tab - here is the output. I have 2 instances running on this compute right now:
'<capabilities>

  <host>
    <uuid>00000000-0000-0000-0000-4061865c2a04</uuid>
    <cpu>
      <arch>x86_64</arch>
      <model>Nehalem</model>
      <vendor>Intel</vendor>
      <topology sockets='1' cores='4' threads='2'/>
      <feature name='invtsc'/>
      <feature name='rdtscp'/>
      <feature name='pdcm'/>
      <feature name='xtpr'/>
      <feature name='tm2'/>
      <feature name='est'/>
      <feature name='smx'/>
      <feature name='vmx'/>
      <feature name='ds_cpl'/>
      <feature name='monitor'/>
      <feature name='dtes64'/>
      <feature name='pbe'/>
      <feature name='tm'/>
      <feature name='ht'/>
      <feature name='ss'/>
      <feature name='acpi'/>
      <feature name='ds'/>
      <feature name='vme'/>
      <pages unit='KiB' size='4'/>
      <pages unit='KiB' size='2048'/>
    </cpu>
    <power_management>
      <suspend_mem/>
    </power_management>
    <migration_features>
      <live/>
      <uri_transports>
        <uri_transport>tcp</uri_transport>
        <uri_transport>rdma</uri_transport>
      </uri_transports>
    </migration_features>
    <topology>
      <cells num='1'>
        <cell id='0'>
          <memory unit='KiB'>16285524</memory>
          <pages unit='KiB' size='4'>3577301</pages>
          <pages unit='KiB' size='2048'>965</pages>
          <distances>
            <sibling id='0' value='10'/>
          </distances>
          <cpus num='8'>
            <cpu id='0' socket_id='0' core_id='0' siblings='0,4'/>
            <cpu id='1' socket_id='0' core_id='1' siblings='1,5'/>
            <cpu id='2' socket_id='0' core_id='2' siblings='2,6'/>
            <cpu id='3' socket_id='0' core_id='3' siblings='3,7'/>
            <cpu id='4' socket_id='0' core_id='0' siblings='0,4'/>
            <cpu id='5' socket_id='0' core_id='1' siblings='1,5'/>
            <cpu id='6' socket_id='0' core_id='2' siblings='2,6'/>
            <cpu id='7' socket_id='0' core_id='3' siblings='3,7'/>
          </cpus>
        </cell>
      </cells>
    </topology>
    <secmodel>
      <model>none</model>
      <doi>0</doi>
    </secmodel>
    <secmodel>
      <model>dac</model>
      <doi>0</doi>
      <baselabel type='kvm'>+64055:+120</baselabel>
      <baselabel type='qemu'>+64055:+120</baselabel>
    </secmodel>
  </host>

  <guest>
    <os_type>hvm</os_type>
    <arch name='i686'>
      <wordsize>32</wordsize>
      <emulator>/usr/bin/qemu-system-i386</emulator>
      <machine maxCpus='255'>pc-i440fx-xenial</machine>
      <machine canonical='pc-i440fx-xenial' maxCpus='255'>ubuntu</machine>
      <machine maxCpus='255'>pc-i440fx-2.4</machine>
      <machine maxCpus='255'>pc-1.3</machine>
      <machine maxCpus='255'>pc-0.12</machine>
      <machine maxCpus='255'>pc-q35-1.6</machine>
      <machine maxCpus='255'>pc-q35-1.5</machine>
      <machine maxCpus='1'>xenpv</machine>
      <machine maxCpus='255'>pc-i440fx-1.6</machine>
      <machine maxCpus='255'>pc-q35-2.2</machine>
      <machine maxCpus='255'>pc-i440fx-vivid</machine>
      <machine maxCpus='255'>pc-0.11</machine>
      <machine maxCpus='255'>pc-i440fx-2.3</machine>
      <machine maxCpus='255'>pc-0.10</machine>
      <machine maxCpus='255'>pc-1.2</machine>
      <machine maxCpus='255'>pc-i440fx-2.2</machine>
      <machine maxCpus='1'>isapc</machine>
      <machine maxCpus='255'>pc-i440fx-1.7</machine>
      <machine maxCpus='255'>pc-q35-xenial</machine>
      <machine maxCpus='255'>pc-q35-1.4</machine>
      <machine maxCpus='255'>pc-i440fx-trusty</machine>
      <machine maxCpus='255'>pc-i440fx-wily</machine>
      <machine maxCpus='128'>xenfv</machine>
      <machine maxCpus='255'>pc-q35-2.5</machine>
      <machine canonical='pc-q35-2.5' maxCpus='255'>q35</machine>
      <machine maxCpus='255'>pc-0.15</machine>
      <machine maxCpus='255'>pc-i440fx-utopic</machine>
      <machine maxCpus='255'>pc-i440fx-1.5</machine>
      <machine maxCpus='255'>pc-0.14</machine>
      <machine maxCpus='255'>pc-q35-2.0</machine>
      <machine maxCpus='255'>pc-i440fx-1.4</machine>
      <machine maxCpus='255'>pc-q35-2.1</machine>
      <machine maxCpus='255'>pc-i440fx-2.5</machine>
      <machine canonical='pc-i440fx-2.5' maxCpus='255'>pc</machine>
      <machine maxCpus='255'>pc-1.1</machine>
      <machine maxCpus='255'>pc-q35-1.7</machine>
      <machine maxCpus='255'>pc-i440fx-2.1</machine>
      <machine maxCpus='255'>pc-1.0</machine>
      <machine maxCpus='255'>pc-i440fx-2.0</machine>
      <machine maxCpus='255'>pc-q35-2.4</machine>
      <machine maxCpus='255'>pc-q35-2.3</machine>
      <machine maxCpus='255'>pc-0.13</machine>
      <domain type='qemu'/>
      <domain type='kvm'>
        <emulator>/usr/bin/kvm-spice</emulator>
        <machine maxCpus='255'>pc-i440fx-xenial</machine>
        <machine canonical='pc-i440fx-xenial' maxCpus='255'>ubuntu</machine>
        <machine maxCpus='255'>pc-i440fx-2.4</machine>
        <machine maxCpus='255'>pc-1.3</machine>
        <machine maxCpus='255'>pc-0.12</machine>
        <machine maxCpus='255'>pc-q35-1.6</machine>
        <machine maxCpus='255'>pc-q35-1.5</machine>
        <machine maxCpus='255'>pc-i440fx-1.6</machine>
        <machine maxCpus='255'>pc-q35-2.2</machine>
        <machine maxCpus='255'>pc-i440fx-1.7</machine>
        <machine maxCpus='255'>pc-i440fx-vivid</machine>
        <machine maxCpus='255'>pc-0.11</machine>
        <machine maxCpus='1'>xenpv</machine>
        <machine maxCpus='255'>pc-q35-2.1</machine>
        <machine maxCpus='255'>pc-q35-xenial</machine>
        <machine maxCpus='255'>pc-0.10</machine>
        <machine maxCpus='255'>pc-1.2</machine>
        <machine maxCpus='255'>pc-i440fx-2.2</machine>
        <machine maxCpus='1'>isapc</machine>
        <machine maxCpus='255'>pc-i440fx-2.3</machine>
        <machine maxCpus='255'>pc-i440fx-trusty</machine>
        <machine maxCpus='255'>pc-q35-1.4</machine>
        <machine maxCpus='255'>pc-i440fx-wily</machine>
        <machine maxCpus='128'>xenfv</machine>
        <machine maxCpus='255'>pc-q35-2.5</machine>
        <machine canonical='pc-q35-2.5' maxCpus='255'>q35</machine>
        <machine maxCpus='255'>pc-0.15</machine>
        <machine maxCpus='255'>pc-i440fx-utopic</machine>
        <machine maxCpus='255'>pc-i440fx-1.5</machine>
        <machine maxCpus='255'>pc-q35-2.0</machine>
        <machine maxCpus='255'>pc-i440fx-1.4</machine>
        <machine maxCpus='255'>pc-i440fx-2.5</machine>
        <machine canonical='pc-i440fx-2.5' maxCpus='255'>pc</machine>
        <machine maxCpus='255'>pc-0.14</machine>
        <machine maxCpus='255'>pc-1.1</machine>
        <machine maxCpus='255'>pc-i440fx-2.1</machine>
        <machine maxCpus='255'>pc-q35-1.7</machine>
        <machine maxCpus='255'>pc-1.0</machine>
        <machine maxCpus='255'>pc-i440fx-2.0</machine>
        <machine maxCpus='255'>pc-q35-2.4</machine>
        <machine maxCpus='255'>pc-q35-2.3</machine>
        <machine maxCpus='255'>pc-0.13</machine>
      </domain>
    </arch>
    <features>
      <cpuselection/>
      <deviceboot/>
      <disksnapshot default='on' toggle='no'/>
      <acpi default='on' toggle='yes'/>
      <apic default='on' toggle='no'/>
      <pae/>
      <nonpae/>
    </features>
  </guest>

  <guest>
    <os_type>hvm</os_type>
    <arch name='x86_64'>
      <wordsize>64</wordsize>
      <emulator>/usr/bin/qemu-system-x86_64</emulator>
      <machine maxCpus='255'>pc-i440fx-xenial</machine>
      <machine canonical='pc-i440fx-xenial' maxCpus='255'>ubuntu</machine>
      <machine maxCpus='255'>pc-i440fx-2.4</machine>
      <machine maxCpus='255'>pc-1.3</machine>
      <machine maxCpus='255'>pc-0.12</machine>
      <machine maxCpus='255'>pc-q35-1.6</machine>
      <machine maxCpus='255'>pc-q35-1.5</machine>
      <machine maxCpus='255'>pc-i440fx-1.6</machine>
      <machine maxCpus='255'>pc-q35-2.2</machine>
      <machine maxCpus='255'>pc-i440fx-1.7</machine>
      <machine maxCpus='255'>pc-i440fx-vivid</machine>
      <machine maxCpus='255'>pc-0.11</machine>
      <machine maxCpus='1'>xenpv</machine>
      <machine maxCpus='255'>pc-q35-2.1</machine>
      <machine maxCpus='255'>pc-q35-xenial</machine>
      <machine maxCpus='255'>pc-0.10</machine>
      <machine maxCpus='255'>pc-1.2</machine>
      <machine maxCpus='255'>pc-i440fx-2.2</machine>
      <machine maxCpus='1'>isapc</machine>
      <machine maxCpus='255'>pc-i440fx-2.3</machine>
      <machine maxCpus='255'>pc-i440fx-trusty</machine>
      <machine maxCpus='255'>pc-q35-1.4</machine>
      <machine maxCpus='255'>pc-i440fx-wily</machine>
      <machine maxCpus='128'>xenfv</machine>
      <machine maxCpus='255'>pc-q35-2.5</machine>
      <machine canonical='pc-q35-2.5' maxCpus='255'>q35</machine>
      <machine maxCpus='255'>pc-0.15</machine>
      <machine maxCpus='255'>pc-i440fx-utopic</machine>
      <machine maxCpus='255'>pc-i440fx-1.5</machine>
      <machine maxCpus='255'>pc-q35-2.0</machine>
      <machine maxCpus='255'>pc-i440fx-1.4</machine>
      <machine maxCpus='255'>pc-i440fx-2.5</machine>
      <machine canonical='pc-i440fx-2.5' maxCpus='255'>pc</machine>
      <machine maxCpus='255'>pc-0.14</machine>
      <machine maxCpus='255'>pc-1.1</machine>
      <machine maxCpus='255'>pc-i440fx-2.1</machine>
      <machine maxCpus='255'>pc-q35-1.7</machine>
      <machine maxCpus='255'>pc-1.0</machine>
      <machine maxCpus='255'>pc-i440fx-2.0</machine>
      <machine maxCpus='255'>pc-q35-2.4</machine>
      <machine maxCpus='255'>pc-q35-2.3</machine>
      <machine maxCpus='255'>pc-0.13</machine>
      <domain type='qemu'/>
      <domain type='kvm'>
        <emulator>/usr/bin/kvm-spice</emulator>
        <machine maxCpus='255'>pc-i440fx-xenial</machine>
        <machine canonical='pc-i440fx-xenial' maxCpus='255'>ubuntu</machine>
        <machine maxCpus='255'>pc-i440fx-2.4</machine>
        <machine maxCpus='255'>pc-1.3</machine>
        <machine maxCpus='255'>pc-0.12</machine>
        <machine maxCpus='255'>pc-q35-1.6</machine>
        <machine maxCpus='255'>pc-q35-1.5</machine>
        <machine maxCpus='255'>pc-i440fx-1.6</machine>
        <machine maxCpus='255'>pc-q35-2.2</machine>
        <machine maxCpus='255'>pc-i440fx-1.7</machine>
        <machine maxCpus='255'>pc-i440fx-vivid</machine>
        <machine maxCpus='255'>pc-0.11</machine>
        <machine maxCpus='1'>xenpv</machine>
        <machine maxCpus='255'>pc-q35-2.1</machine>
        <machine maxCpus='255'>pc-q35-xenial</machine>
        <machine maxCpus='255'>pc-0.10</machine>
        <machine maxCpus='255'>pc-1.2</machine>
        <machine maxCpus='255'>pc-i440fx-2.2</machine>
        <machine maxCpus='1'>isapc</machine>
        <machine maxCpus='255'>pc-i440fx-2.3</machine>
        <machine maxCpus='255'>pc-i440fx-trusty</machine>
        <machine maxCpus='255'>pc-q35-1.4</machine>
        <machine maxCpus='255'>pc-i440fx-wily</machine>
        <machine maxCpus='128'>xenfv</machine>
        <machine maxCpus='255'>pc-q35-2.5</machine>
        <machine canonical='pc-q35-2.5' maxCpus='255'>q35</machine>
        <machine maxCpus='255'>pc-0.15</machine>
        <machine maxCpus='255'>pc-i440fx-utopic</machine>
        <machine maxCpus='255'>pc-i440fx-1.5</machine>
        <machine maxCpus='255'>pc-q35-2.0</machine>
        <machine maxCpus='255'>pc-i440fx-1.4</machine>
        <machine maxCpus='255'>pc-i440fx-2.5</machine>
        <machine canonical='pc-i440fx-2.5' maxCpus='255'>pc</machine>
        <machine maxCpus='255'>pc-0.14</machine>
        <machine maxCpus='255'>pc-1.1</machine>
        <machine maxCpus='255'>pc-i440fx-2.1</machine>
        <machine maxCpus='255'>pc-q35-1.7</machine>
        <machine maxCpus='255'>pc-1.0</machine>
        <machine maxCpus='255'>pc-i440fx-2.0</machine>
        <machine maxCpus='255'>pc-q35-2.4</machine>
        <machine maxCpus='255'>pc-q35-2.3</machine>
        <machine maxCpus='255'>pc-0.13</machine>
      </domain>
    </arch>
    <features>
      <cpuselection/>
      <deviceboot/>
      <disksnapshot default='on' toggle='no'/>
      <acpi default='on' toggle='yes'/>
      <apic default='on' toggle='no'/>
    </features>
  </guest>

</capabilities>
'

**Comment by catborise** [comment]
i test it on two machines it works(oel/centos/rhel). but it think your problem is related with ubuntu.
emulator info must be populate right. if it is not. some informations like video types and bus types does not get from libvirt. then vm create operation not start.

i should check it with ubuntu to see what is the difference..

**Comment by Bandic007** [comment]
Yes when I am creating instance video info is not populated. Also my host on which I am running webvirtcloud runs on ubuntu. Do you want to give you access to a vm with ubuntu on which I have yor version of the repo installed and running. You can make your tests there?

**Comment by catborise** [comment]
thanks, no need. i am installing ubuntu 18 now. i can test it there. i need kvm/libvirt on ubuntu. webvirtcloud is unnecessary.

**Comment by Bandic007** [comment]
@catborise can you give me a mail address? I wanted to create a slack closes group chat with you and @honza81 so that we can discuss easily there - if you think it will be helpful?

**Comment by catborise** [comment]
there is not any problem with ubuntu 18. which version of libvirt you are using?
i can create vm without any problem. 
image

**Comment by Bandic007** [comment]
Ah in fact my host is running ubuntu 16.04 I guess I should upgrade

**Comment by catborise** [comment]
i dont think so. it should work with ubuntu 16.  i need "virsh capabilites" command output your host.

**Comment by catborise** [comment]
i think github removes xml tags.. it is not useful. i will install ubuntu16 to see results.

**Comment by catborise** [comment]
the problem is related with "libvirt". libvirt version on ubuntu 16 is too old(on ubuntu 1.3.1, latest : 4.7.0).
i add a patch which adds default graphics type manually.

and there is not any problem with emulator. it works as expected.
ubuntu 16.04 - host
image

**Comment by Bandic007** [comment]
aahhh great, thank you!  I've upgraded one of my computes to 18.04 and it is running more than fine there.

**Comment by retspen** [comment]
Thank you. Great job!

**Pull request merged**
