### PR TITLE
Add Qos for Network Functions

### PR DESCRIPTION
**Pull request by catborise**
Hi retspen,

- Add qos functions for network: Inbound & Outbound

### CODE REVIEW

**Comment by lord-kyron** [comment]
Hey @catborise - can you make this function to be available the same way as for example adding new static addresses - with green+ button in the network settings? I would like to be possible to add new bandwidth shaping rules for VMs directly from boxes in the UI.

**Comment by catborise** [comment]
yes you can do it like static address. But bandwith shaping operations could not be done when the network is started. If you want to add inbound/outbound qos to network, it must be done while it is stopped.

Qos Config works network for now. But i think we also could add qos config for vm. But i should research it. if it is possible, i will add it.

**Comment by retspen** [comment]
Thank you!

**Comment by lord-kyron** [comment]
@catborise - grat, thank you!

**Pull request merged**
